let btn = document.getElementById("btn");
let output = document.getElementById("output");
let quotes = [
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr.",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "The best way to predict the future is to create it. – Peter Drucker",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
  "The harder the conflict, the greater the triumph. – George Washington",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "You miss 100% of the shots you don't take. – Wayne Gretzky",
  "The question isn't who is going to let me; it's who is going to stop me. – Ayn Rand",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
  "Don't let yesterday take up too much of today. – Will Rogers",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Dream big and dare to fail. – Norman Vaughan",
  "Your life does not get better by chance, it gets better by change. – Jim Rohn",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character. – Unknown",
  "The man who has confidence in himself gains the confidence of others. – Hasidic Proverb",
  "The future depends on what you do today. – Mahatma Gandhi",
  "With the new day comes new strength and new thoughts. – Eleanor Roosevelt",
  "The only limit to your impact is your imagination and commitment. – Tony Robbins",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "The best revenge is massive success. – Frank Sinatra",
  "If you can’t explain it simply, you don’t understand it well enough. – Albert Einstein",
  "To win big, you sometimes have to take big risks. – Bill Gates",
  "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Quality is not an act, it is a habit. – Aristotle",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life. – Naeem Callaway",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible. – Francis of Assisi",
  "Don’t wait. The time will never be just right. – Napoleon Hill",
  "Try not to become a man of success, but rather try to become a man of value. – Albert Einstein",
  "Stay away from those people who try to disparage your ambitions. Small minds always do that. – Mark Twain",
  "Everything you can imagine is real. – Pablo Picasso",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Don't watch the clock; do what it does—keep going. – Sam Levenson",
  "Whether you think you can or you think you can't, you're right. – Henry Ford",
  "The biggest risk is not taking any risk. – Mark Zuckerberg",
  "Perseverance is failing 19 times and succeeding the 20th. – Julie Andrews",
  "Don't let what you cannot do interfere with what you can do. – John Wooden",
  "The journey of a thousand miles begins with one step. – Lao Tzu",
  "Believe and act as if it were impossible to fail. – Charles Kettering",
  "You must do the thing you think you cannot do. – Eleanor Roosevelt",
  "What seems to us as bitter trials are often blessings in disguise. – Oscar Wilde",
  "If opportunity doesn’t knock, build a door. – Milton Berle",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Ryun",
  "Success isn’t overnight. It’s when every day you get a little better than the day before. It adds up. – Dwayne Johnson",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Don't count the days, make the days count. – Muhammad Ali",
  "You don’t drown by falling in the water; you drown by staying there. – Edwin Louis Cole",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "It's not whether you get knocked down; it's whether you get up. – Vince Lombardi",
  "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "A year from now you may wish you had started today. – Karen Lamb",
  "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
  "Failure is the condiment that gives success its flavor. – Truman Capote",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
  "To handle yourself, use your head; to handle others, use your heart. – Eleanor Roosevelt",
  "Be not afraid of life. Believe that life is worth living. – William James",
  "Do not wait to strike till the iron is hot; but make it hot by striking. – William Butler Yeats",
  "If you really look closely, most overnight successes took a long time. – Steve Jobs",
  "A goal is not always meant to be reached; it often serves simply as something to aim at. – Bruce Lee",
  "You can’t cross the sea merely by standing and staring at the water. – Rabindranath Tagore",
  "Everything has beauty, but not everyone sees it. – Confucius",
  "You will succeed because most people are lazy. – Shahir Zag",
  "I never dreamed about success. I worked for it. – Estée Lauder",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "The future starts today, not tomorrow. – Pope John Paul II",
  "What you do today can improve all your tomorrows. – Ralph Marston",
  "A champion is someone who gets up when he can’t. – Jack Dempsey",
  "Act as if what you do makes a difference. It does. – William James",
  "The best dreams happen when you're awake. – Cherie Gilderbloom",
  "Small deeds done are better than great deeds planned. – Peter Marshall",
  "Don’t limit your challenges. Challenge your limits. – Jerry Dunn",
  "You don’t have to see the whole staircase, just take the first step. – Martin Luther King Jr."
];


btn.addEventListener("click", function() {
  let randomIndex = Math.floor(Math.random() * quotes.length);
  output.innerHTML = quotes[randomIndex];
});